services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dung@123
    ports:
      - "1444:1433"
    volumes:
      - social_network_server_mssql_data:/var/opt/mssql

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # UI
      - "1883:1883" # MQTT (TCP)
      - "15675:15675" # MQTT over WebSocket
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: bash -lc "rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt && rabbitmq-server"

  authentication_service:
    build:
      context: . # root solution
      dockerfile: authentication_service/Dockerfile
    image: nguyenducdung/social-authentication-service:1.0.0
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=mssql,1433;Database=Authentication;User Id=sa;Password=Dung@123;Encrypt=False;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379
      - Redis__ServicePrefix=auth
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_PORT=5672
    depends_on:
      - mssql
      - redis
      - rabbitmq
    ports:
      - "5001:8080"

  authorization_service:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src/authorization_service
    command: bash -lc "dotnet restore && dotnet watch run --urls http://0.0.0.0:8081"
    volumes:
      - ./authorization_service:/src/authorization_service
      - ./infrastructure:/src/infrastructure
      - nuget_cache:/root/.nuget/packages
      - ./dataprotection_keys:/keys
    environment:
      - ASPNETCORE_URLS=http://+:8081
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=mssql,1433;Database=Authorization;User Id=sa;Password=Dung@123;Encrypt=False;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379
      - Redis__ServicePrefix=authz
    ports:
      - "5002:8081"
  mail_service:
    build:
      context: .
      dockerfile: mail_service/Dockerfile
    image: nguyenducdung/social-mail-service:1.0.0
    environment:
      ASPNETCORE_URLS: "http://+:8082"
      ASPNETCORE_ENVIRONMENT: "Development"

      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASS: "guest"
      RABBITMQ_PORT: "5672"

      Smtp__Host: smtp.gmail.com
      Smtp__Port: "587"
      Smtp__UseStartTls: "true"
      Smtp__User: "duccdung999@gmail.com"
      Smtp__Pass: "epwzvvnaxqybdqlc"
      Email__FromName: "Social Network"
      Email__FromAddress: "duccdung999@gmail.com"
    depends_on:
      - rabbitmq
    ports:
      - "5003:8082"

  chat_service:
    build:
      context: . # root solution
      dockerfile: chat_service/Dockerfile
    image: nguyenducdung/social-chat-service:1.0.0
    environment:
      - ASPNETCORE_URLS=http://+:8083
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=mssql,1433;Database=texting_services;User Id=sa;Password=Dung@123;Encrypt=False;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379
      - Redis__ServicePrefix=chat
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_PORT=5672
    depends_on:
      - mssql
      - redis
      - rabbitmq
    ports:
      - "5004:8083"

  profile_service:
    build:
      context: .
      dockerfile: profile_service/Dockerfile
    image: nguyenducdung/social-profile-service:1.0.0
    environment:
      - ASPNETCORE_URLS=http://+:8084
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_PORT=5672
      - ConnectionStrings__SqlServer=Server=mssql,1433;Database=profile;User Id=sa;Password=Dung@123;Encrypt=False;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379
      - Redis__ServicePrefix=profile
    depends_on:
      - mssql
      - redis
      - rabbitmq
    ports:
      - "5005:8084"

  media_service:
    build:
      context: .
      dockerfile: media_services/Dockerfile
    image: nguyenducdung/social-media-service:1.0.0
    environment:
      - ASPNETCORE_URLS=http://+:8086
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_PORT=5672
      - ConnectionStrings__SqlServer=Server=mssql,1433;Database=Media;User Id=sa;Password=Dung@123;Encrypt=False;TrustServerCertificate=True;
      - ConnectionStrings__MLSql=Data Source=SQL8020.site4now.net,1433;Initial Catalog=db_abf02f_social;User Id=db_abf02f_social_admin;Password=Dung@123;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379
      - Redis__ServicePrefix=media
    depends_on:
      - mssql
      - redis
      - rabbitmq
    ports:
      - "5006:8086"

  notification_service:
    build:
      context: . # root solution
      dockerfile: notification_service/Dockerfile
    image: nguyenducdung/social-notification-service:1.0.0
    environment:
      - ASPNETCORE_URLS=http://+:8087
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_PORT=5672
      - ConnectionStrings__SqlServer=Server=mssql,1433;Database=notification;User Id=sa;Password=Dung@123;Encrypt=False;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379
      - Redis__ServicePrefix=notification
    depends_on:
      - mssql
      - redis
      - rabbitmq
    ports:
      - "5007:8087"

  api_getway_service:
    build:
      context: .
      dockerfile: api_getway_service/Dockerfile
    image: nguyenducdung/social-api-gateway:1.0.0
    environment:
      - ASPNETCORE_URLS=http://+:8085
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - authentication_service
      - authorization_service
      - profile_service
      - media_service
      - chat_service
      - notification_service
    ports:
      - "5000:8085"

volumes:
  redis_data:
  nuget_cache:
  rabbitmq_data:
  social_network_server_mssql_data:
